### ISSUE TITLE
Move the vendoring tool to dep

### ISSUE THREAD

**Issue by dungeonmaster18** [openfaas/certify-incubator#1]
**Description:**
As we are moving all the repo to dep vendoring tool. Here is the proposal [openfaas/faas/issue#462](https://github.com/openfaas/faas/issues/462). This repo also should use dep.

For help: https://github.com/openfaas/faas-cli/pull/282. please check this.

**Comment by dungeonmaster18** [comment]
You can work on this @sterchelen

**Comment by sterchelen** [comment]
Ok ! I take it :)
